### ISSUE TITLE
Field 'exclude_slug_for_subpages' does not work since TYPO3 9.5.14

### ISSUE THREAD

**Issue by hirnsturm** [b13/masi#11] opened 2020-03-10 14:13 UTC
It seams that field 'exclude_slug_for_subpages' does not work since TYPO3 9.5.14. Path segmet is still in URL path of subpages.

If I downgrade to TYPO3 9.4.13 it works as expected.

**Comment by moe2k** [comment] 2020-05-05 16:35
Does the Problem still exist after upgrading to 9.5.16? I could not reproduce it there.

**Comment by dmitryd** [comment] 2020-11-18 08:08
Works fine for me in 9.5.22.

@bmack I guess this can be closed...

**Comment by bmack** [comment] 2020-11-18 09:54
Thanks for the verification @moe2k and @dmitryd ! will close this one for now

**Closed as completed by bmack** 2020-11-18 09:54 UTC
